edit README.md
systopia/funding pull request #194
Opened 2024-01-04 13:06 UTC by TychoSchottelius

- first step

2024-01-04 13:08 UTC, TychoSchottelius commented
Just a starting description to make the readme alive. please quickly confirm.

2024-01-04 13:35 UTC, dontub requested changes

2024-01-04 13:35 UTC, dontub commented on README.md
> +This extension forms the basis for application management in CiviCRM: manage funding programs from application to payout.
I'd suggest to use `funding application management` at this point as it is the first time the term `application` is used.

2024-01-04 13:35 UTC, dontub commented on README.md
> +The process of submitting and processing funding applications can be centralised:
Should be `centralized` in correspondence to the already used AE strings.

2024-01-04 13:35 UTC, dontub commented on README.md
> +In order to map the complex process in its entirety, this extension should be supplemented with the following:
I think we should list all extensions required in the `info.xml` (apart from the Civi core extensions) and call them `requirements` or `dependencies`. To me `should be supplemented` indicates that they are optional. Maybe we can skip them here as they will be part of the [install documentation](https://github.com/systopia/funding/blob/add-documentation/docs/installation.md)...

2024-01-08 15:54 UTC, TychoSchottelius commented
All requested changes done.

2024-01-08 16:24 UTC, dontub approved these changes

2024-01-08 16:24 UTC, merged